version: '3.8'
services:
    # nginx:
    #   image: nginx:alpine
    #   container_name: docker-project-nginx
    #   working_dir: /application
    #   volumes:
    #       - .:/application
    #       - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #   ports:
    #       - 89:80

    php-fpm: 
      build: docker/php-fpm
      container_name: lumen_service
      working_dir: /application
      volumes:
        - .:/application
      command: "php -S 0.0.0.0:9000 -t public" 
      ports:
      - "9000:9000"
      depends_on:
      - "database"
             
    database:
      image: mysql:latest
      container_name: database_service
      volumes:
        - ./docker/database:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      ports:
        - "3307:3306"
